server:
  port: 9001

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
      username: user
      password: password
      url: jdbc:postgresql://localhost:5432/catalog_db
      hikari:
        connection-timeout: 2000
        maximum-pool-size: 5
  sql:  #To init tables in schema
    init:
      mode: always
