version: "3.8"
services:
  catalog-service:
    depends_on:
      - postgres
      - config-server
    image: "kehinde/catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/catalog_db
      - SPRING_PROFILES_ACTIVE=testdata

  config-server:
    image: "kehinde/config-server"
    container_name: "config-server"
    ports:
      - 8888:8888

  postgres:
    image: "postgres:14.4"
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=catalog_db
