server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: gateway
  lifecycle:
    timeout-per-shutdown-phase: 15s

  cloud:
    gateway:
      routes:
        - id: catalog-route
          uri: ${CATALOG_SERVICE_URL:http://catalog-service:9001}/books
          predicates:
            - Path=/books/**
        - id: order-route
          uri: ${ORDER_SERVICE_URL:http://order-service:9002}/orders
          predicates:
            - Path=/orders/**
        - id: user-route
          uri: ${USER_SERVICE_URL:http://user-service:9003}/users
          predicates:
            - Path=/users/**
